### ISSUE TITLE
Summer cleanup

### ISSUE THREAD

**Issue by markaren** [markaren/threepp#115]
More intrusive changes than normal will be scheduled during the summer

- [x] Remove deprecated functions (#148)
- [x] Remove FPS from canvas (c9fd872)
- [x] Remove timings from canvas (#148)
- [x] Use Catch2 v3 (#151)
- [x] Allow non-owning add for Object3D (fb9d8fa40db102a17bfa01eaec1d2eab2440d407)
- [x] Decouple GLRenderer from Canvas (#161)
- [x] Replacing int constants with Enums (#150) (mostly done)
- [x] Remove URLFetcer (#159)
- [x] Stack allocation of Object3D types (7ceb34f288d4498d7fff64c88d1f040881dee52f)
- [x] Decouple text rendering from GLRenderer  (#167)

Things to look at in the future:

~- [ ] Rethink physics integration~
~- [ ] Rethink BufferAttributes~
~- [ ] Less public fields~
~- [ ] Make it easier to add EventListeners~
~- [ ] Target C++20~

**Comment by markaren** [comment]
Mac is holding C++20 targeting back....

**Comment by Kevin-Delnoije** [comment]
have you considered jolt physics? It is tested in a AAA game and now starting to be adopted by godot game engine. also it has some support for js with [emscripten]( https://github.com/jrouwe/JoltPhysics.js/tree/main)

**Comment by markaren** [comment]
> have you considered jolt physics?

Not heard about it before. I did a quick check, but unfortunatly the vcpkg package is incomplete and the sample code was overly complex compared to say bullet and similar. 

I might come back to it in the future. But at the same time, threepp is not focused in physics. I might even remove the bullet example code at some point.
